version: '3.8'

services:
  dart-agent:
    build: .
    container_name: dart-agent-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      # 개발 시 데이터 파일 공유 (선택사항)
      - ./data:/app/data:ro 
